### ISSUE TITLE
Pipsi Install Fails | Fails to create virtualenv

### ISSUE THREAD

**Issue by zeknox** [blark/aiodnsbrute#1]
I've tried following the documentation for installing aiodnsbrute but having some issues.  I'm running on MAC OS X so not sure if that is part of the issue but I've installed virtualenv via brew, and also installed pipsi as documented in the README file.

Where I have issues is when I attempt to invoke: `pipsi install .` from within the repo directory.  Here is the output I receive:
<pre>
$ pipsi install .
Running virtualenv with interpreter /Users/user/.local/venvs/pipsi/bin/python3.6
Using base prefix '/usr/local/Cellar/python/3.6.4_3/bin/../Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/user/.local/venvs/aiodnsbrute/bin/python3.6
Also creating executable in /Users/user/.local/venvs/aiodnsbrute/bin/python
ERROR: The executable /Users/user/.local/venvs/aiodnsbrute/bin/python3.6 is not functioning
ERROR: It thinks sys.prefix is '/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6' (should be '/Users/user/.local/venvs/aiodnsbrute')
ERROR: virtualenv is not compatible with this system or executable
Failed to create virtualenv.  Aborting.
</pre>

Note that the python3.6 binary it seems to depends on does not exist for me:
<pre>
$ file /Users/user/.local/venvs/aiodnsbrute/bin/python3.6
/Users/user/.local/venvs/aiodnsbrute/bin/python3.6: cannot open `/Users/user/.local/venvs/aiodnsbrute/bin/python3.6' (No such file or directory)
</pre>

Any assistance would be greatly appreciated. Cheers!

**Comment by blark** [comment]
Let me do some troubleshooting and get back to you. Mac OS is a pain due to the default Python 2.

**Comment by blark** [comment]
I suspect this is due to a Python problem. Make sure you have a functioning Python3 environment, at least 3.5 but preferably 3.7. You can install it on Mac with brew. Let me know if this is still a problem!
