### ISSUE TITLE
Import Domains From File

### ISSUE THREAD

**Issue by zeknox** [blark/aiodnsbrute#4]
As a potential feature request. It would be great if aiodnsbrute would import a list of domains from a file. This would be quite useful to perform sub-domain enumeration across multiple domains.

**Comment by blark** [comment]
Hey @zeknox I'd rather leave this to some simple bash scripting for now as it complicates output and some other stuff. I'm going to close this for now. I think this is easy enough: 
```
while read p; do
  aiodnsbrute -o json "$p"
done < domains_to_brute.txt
```

**Comment by zeknox** [comment]
Thanks for the update!
