### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by fabaff** [blark/aiodnsbrute#5]
The `setup.py` file says the license is  [BSD](https://github.com/blark/aiodnsbrute/blob/e773a4c790b7177cad212d24ee8d0787d04e5b39/setup.py#L13) but the `LICENSE.txt` file that it's GPLv3.

Which one is the right license?

**Comment by blark** [comment]
Ack. Setup was from an example - fixed in dev branch, will merge changes after some testing. GPLv3.
